#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Smart-Comments
Version  : 1.06
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/N/NE/NEILB/Smart-Comments-1.06.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/N/NE/NEILB/Smart-Comments-1.06.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libs/libsmart-comments-perl/libsmart-comments-perl_1.06-1.debian.tar.xz
Summary  : 'Comments that do more than just sit there'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Smart-Comments-license
Requires: perl-Smart-Comments-man

%description
Smart::Comments
Smart comments provide an easy way to insert debugging and tracking code
into a program. They can report the value of a variable, track the
progress of a loop, and verify that particular assertions are true.

%package license
Summary: license components for the perl-Smart-Comments package.
Group: Default

%description license
license components for the perl-Smart-Comments package.


%package man
Summary: man components for the perl-Smart-Comments package.
Group: Default

%description man
man components for the perl-Smart-Comments package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Smart-Comments-1.06
mkdir -p %{_topdir}/BUILD/Smart-Comments-1.06/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Smart-Comments-1.06/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Smart-Comments
cp LICENSE %{buildroot}/usr/share/doc/perl-Smart-Comments/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Smart/Comments.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Smart-Comments/LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Smart::Comments.3
